//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Slalom.Boost.VisualStudio.Projects.Module.Application.Commands.Files {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Templates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Templates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Slalom.Boost.VisualStudio.Projects.Module.Application.Commands.Files.Templates", typeof(Templates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///using Slalom.Boost.Commands;
        ///using Slalom.Boost.Domain;
        ///using System.Threading.Tasks;
        ///
        ///namespace {{RootNamespace}}
        ///{
        ///	// TODO: Update handle method
        ///    // TODO: Add unit tests
        ///	// TODO: Add the return type to the command if this command returns data (ie {{Name}}Command : Command&lt;Guid&gt;)
        ///
        ///    /// &lt;summary&gt;
        ///    /// Handles/Processes the &lt;seealso cref=&quot;{{Name}}Command&quot;/&gt; command.
        ///    /// &lt;/summary&gt;
        ///	/// &lt;seealso cref=&quot;{{Name}}Command&quot;/&gt;
        ///    /// &lt;seealso href=&quot;https://www.safariboo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AddCommandHandler {
            get {
                return ResourceManager.GetString("AddCommandHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///
        ///using Slalom.Boost.Domain;
        ///using Slalom.Boost.Validation;
        ///
        ///namespace {{RootNamespace}}.Application.{{Namespace}}.Rules
        ///{
        ///    // TODO: Update the description [description]
        ///	// TODO: Update class name
        ///    // TODO: Set the correct order
        ///    // TODO: Implement validation
        ///    // TODO: Add unit tests
        ///
        ///    /// &lt;summary&gt;
        ///    /// Validates the &lt;seealso cref=&quot;{{Name}}Command&quot; /&gt; to ensure it complies with the business rule [descriptio [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BusinessValidationRule {
            get {
                return ResourceManager.GetString("BusinessValidationRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using Slalom.Boost.Commands;
        ///
        ///namespace {{RootNamespace}}.Application.{{Name}}
        ///{
        ///    // TODO: Update the task description [task]    
        ///    // TODO: Use the context menu to add an input validation rule
        ///    // TODO: Use the context menu to add any security rules
        ///    // TODO: Use the context menu to add any business rules
        ///    // TODO: Use the context menu to add integration tests
        ///	// TODO: Update the documentation URL [Documentation URL]
        ///
        ///    /// &lt;summary&gt;
        ///    /// An imperative message [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Command {
            get {
                return ResourceManager.GetString("Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///using Slalom.Boost.Commands;
        ///using Slalom.Boost.Domain;
        ///using System.Threading.Tasks;
        ///
        ///namespace {{RootNamespace}}
        ///{
        ///	// TODO: Update handle method
        ///    // TODO: Add unit tests
        ///	// TODO: Add the return type to the command if this command returns data (ie {{Name}}Command : Command&lt;Guid&gt;)
        ///
        ///    /// &lt;summary&gt;
        ///    /// Handles/Processes the &lt;seealso cref=&quot;{{Name}}Command&quot;/&gt; command.
        ///    /// &lt;/summary&gt;
        ///	/// &lt;seealso cref=&quot;{{Name}}Command&quot;/&gt;
        ///    /// &lt;seealso href=&quot;https://www.safariboo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CommandHandler {
            get {
                return ResourceManager.GetString("CommandHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using Slalom.Boost.Domain.Concepts;
        ///using Slalom.Boost.Validation;
        ///using Slalom.Boost.Validation.Rules;
        ///using System.Collections.Generic;
        ///
        ///namespace {{RootNamespace}}.Application.{{Namespace}}.Rules
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Validates the input of the &lt;seealso cref=&quot;{{Name}}Command&quot;/&gt; for basic correctness.
        ///    /// &lt;/summary&gt;
        ///    /// &lt;remarks&gt;
        ///    /// Only simple validation should be done in the input validation rule.  Domain rules should be implemented
        ///    /// in the domain.  Some basic rules [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InputValidationRuleSet {
            get {
                return ResourceManager.GetString("InputValidationRuleSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using Slalom.Boost.Validation;
        ///
        ///namespace {{RootNamespace}}.Application.{{Namespace}}.Rules
        ///{
        ///	// TODO: Update with URL to roles [URL to Roles]
        ///	// TODO: Update with Role name [Role]
        ///	// TODO: Update class name
        ///	// TODO: Update user facing message with [role] and [perform task].
        ///    
        ///	/// &lt;summary&gt;
        ///    /// Validates the &lt;see cref=&quot;{{Command}}&quot;/&gt; by ensuring that the user executing the command is in the &lt;see href=&quot;[URL to Roles]&quot;&gt;[Role]&lt;/see&gt; role.
        ///    /// &lt;/summary&gt;
        ///    public cla [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InRoleValidationRule {
            get {
                return ResourceManager.GetString("InRoleValidationRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading;
        ///using System.Threading.Tasks;
        ///using Slalom.Boost.Commands;
        ///
        ///namespace {{RootNamespace}}.Application.{{Name.Pluralize()}}
        ///{
        ///	/// &lt;summary&gt;
        ///    /// Provides a mediator for processes around {{Name.Pluralize()}}.
        ///    /// &lt;/summary&gt;
        ///    /// &lt;remarks&gt;
        ///    /// In a complex system that you have modeled using aggregates and bounded contexts, there may be some business processes that involve mul [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProcessManager {
            get {
                return ResourceManager.GetString("ProcessManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using Slalom.Boost.Commands;
        ///
        ///namespace {{RootNamespace}}.Application.{{Name.Pluralize()}}.{{Verb}}
        ///{
        ///    // TODO: Update the task description [task]    
        ///    // TODO: Use the context menu to add an input validation rule
        ///    // TODO: Use the context menu to add any security rules
        ///    // TODO: Use the context menu to add any business rules
        ///    // TODO: Use the context menu to add integration tests
        ///	// TODO: Update the documentation URL [Documentation URL]
        ///
        ///    /// &lt;summary&gt;
        ///    ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProcessManagerCommand {
            get {
                return ResourceManager.GetString("ProcessManagerCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Linq;
        ///using Slalom.Boost.Commands;
        ///
        ///namespace {{RootNamespace}}.Query{{Name.Pluralize()}}
        ///{
        ///    // TODO: Update the task description [task]    
        ///    // TODO: Add any security rules
        ///	// TODO: Update the documentation URL [Documentation URL]
        ///
        ///    /// &lt;summary&gt;
        ///    /// An imperative message to [task].
        ///    /// &lt;/summary&gt;
        ///	/// &lt;seealso href=&quot;[Documentation URL]&quot;/&gt;
        ///    public class Query{{Name.Pluralize()}}Command : Command&lt;IQueryable&lt;{{Name}}ReadModel&gt;&gt;
        ///    {
        ///        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string QueryCommand {
            get {
                return ResourceManager.GetString("QueryCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///using Slalom.Boost.Commands;
        ///using Slalom.Boost.Domain;
        ///using System.Threading.Tasks;
        ///
        ///namespace {{RootNamespace}}
        ///{
        ///    // TODO: Add unit tests
        ///	// TODO: Add any expressions to the query
        ///
        ///    /// &lt;summary&gt;
        ///    /// Handles/Processes the &lt;seealso cref=&quot;{{Name}}Command&quot;/&gt; command.
        ///    /// &lt;/summary&gt;
        ///	/// &lt;seealso cref=&quot;{{Name}}Command&quot;/&gt;
        ///    /// &lt;seealso href=&quot;https://www.safaribooksonline.com/library/view/microsoft-net-architecting/9780133986419/ch10.html&quot;&gt;Microsoft .NET: Archit [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string QueryCommandHandler {
            get {
                return ResourceManager.GetString("QueryCommandHandler", resourceCulture);
            }
        }
    }
}
