//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Slalom.Boost.VisualStudio.Projects.Module.UnitTests.Files {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Templates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Templates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Slalom.Boost.VisualStudio.Projects.Module.UnitTests.Files.Templates", typeof(Templates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using Machine.Specifications;
        ///using System.Linq;
        ///
        ///namespace {{RootNamespace}}.UnitTests.Application.Commands.{{Name}}
        ///{
        ///    public class When_validating_{{Rule}}_for_a_{{NameSnakeCase}}_command : given.a_configured_{{Rule}}_rule
        ///    {
        ///		Establish context = () =&gt;
        ///        {
        ///        //    Repository.Setup(e =&gt; e.Query&lt;User&gt;()).Returns(new[] { new User { UserName = &quot;test&quot; } }.AsQueryable());
        ///        };
        ///        
        ///		Because of = () =&gt; ValidateCommand({{DefaultArguments}});
        ///
        ///        Mac [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BusinessValidationUnitTest {
            get {
                return ResourceManager.GetString("BusinessValidationUnitTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///
        ///using {{RootNameSpace}}.Application.Commands.{{Name}};
        ///using {{RootNameSpace}}.Application.Commands.{{Name}}.Rules;
        ///
        ///using Slalom.Boost.Validation;
        ///using Slalom.Boost.Domain;
        ///
        ///using Machine.Specifications;
        ///using Moq;
        ///
        ///namespace {{RootNameSpace}}.UnitTests.Application.Commands.{{Name}}.given
        ///{
        ///	[Subject(typeof({{Rule}}))]
        ///    public class a_configured_{{Rule}}_rule
        ///    {
        ///        protected static {{Rule}} Rule;
        ///
        ///        pr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BusinessValidationUnitTestSetup {
            get {
                return ResourceManager.GetString("BusinessValidationUnitTestSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using Machine.Specifications;
        ///
        ///namespace {{RootNameSpace}}.UnitTests.Application.Commands.{{Name}}
        ///{
        ///    public class When_handling_a_{{NameSnakeCase}}_command : given.a_configured_{{NameSnakeCase}}_command_handler
        ///    {
        ///        private Because of = () =&gt; HandleCommand({{DefaultArguments}});
        ///
        ///        private It should = () =&gt; 1.ShouldEqual(2);
        ///    }
        ///}.
        /// </summary>
        internal static string CommandHandlerUnitTest {
            get {
                return ResourceManager.GetString("CommandHandlerUnitTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using Slalom.Boost.Domain;
        ///using {{RootNamespace}}.Application.Commands.{{Name}};
        ///using {{RootNameSpace}}.Application.Commands.{{Name}}.Rules;
        ///using Machine.Specifications;
        ///using Moq;
        ///
        ///namespace {{RootNamespace}}.UnitTests.Application.Commands.{{Name}}.given
        ///{
        ///    [Subject(typeof({{Name}}CommandHandler))]
        ///    public class a_configured_{{NameSnakeCase}}_command_handler
        ///    {
        ///        protected static Mock&lt;IRepository&gt; Repository;
        ///        protected static {{Name}}CommandHandler Handl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CommandHandlerUnitTestSetup {
            get {
                return ResourceManager.GetString("CommandHandlerUnitTestSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using Machine.Specifications;
        ///
        ///namespace {{RootNameSpace}}.UnitTests.Application.Commands.{{Name}}
        ///{
        ///    public class When_validating_{{NameSnakeCase}}_command_input_with_invalid_input : given.a_configured_{{Rule}}_rule
        ///    {
        ///        Because of = () =&gt; ValidateCommand({{DefaultArguments}});
        ///
        ///        It should_have_a_validation_results = () =&gt; Result.ShouldNotBeEmpty();
        ///    }
        ///}.
        /// </summary>
        internal static string InputValidationUnitTest {
            get {
                return ResourceManager.GetString("InputValidationUnitTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///
        ///using {{Namespace}};
        ///using {{UpperNamespace}};
        ///
        ///using Slalom.Boost.Validation;
        ///
        ///using Machine.Specifications;
        ///
        ///namespace {{RootNameSpace}}.UnitTests.Application.Commands.{{Name}}.given
        ///{
        ///	[Subject(typeof({{Rule}}))]
        ///    public class a_configured_{{Rule}}_rule
        ///    {
        ///        protected static {{Rule}} Rule;
        ///
        ///        protected static {{Name}}Command Command;
        ///
        ///        protected static List&lt;ValidationMessage&gt; Result;
        ///
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InputValidationUnitTestSetup {
            get {
                return ResourceManager.GetString("InputValidationUnitTestSetup", resourceCulture);
            }
        }
    }
}
