//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Slalom.Boost.VisualStudio.Projects.Module.Application.Queries.Files {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Templates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Templates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Slalom.Boost.VisualStudio.Projects.Module.Application.Queries.Files.Templates", typeof(Templates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using Slalom.Boost.Queries;
        ///
        ///namespace {{RootNamespace}}.Application.{{RelativeNamespace}}
        ///{
        ///	// TODO: Update the purpose of the read model [purpose]
        ///
        ///    /// &lt;summary&gt;
        ///    /// Provides a read model for [purpose].
        ///    /// &lt;/summary&gt;
        ///    /// &lt;seealso cref=&quot;IReadModelFacade&quot; /&gt;
        ///    /// &lt;seealso cref=&quot;IUpdateReadModel{TReadModel}&quot; /&gt;
        ///    /// &lt;seealso href=&quot;https://www.safaribooksonline.com/library/view/microsoft-net-architecting/9780133986419/ch11.html&quot;&gt;Microsoft .NET: Architecting Ap [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReadModel {
            get {
                return ResourceManager.GetString("ReadModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace {{RootNamespace}}.Application.{{Name.Pluralize()}}
        ///{
        ///    // TODO: Add descriptions for the queries
        ///    // TODO: Remove any unnecessary queries
        ///    // TODO: Add any additional queries
        ///
        ///    /// &lt;summary&gt;
        ///    /// Contains specific queries for {{Name.Humanize(LetterCasing.LowerCase)}} queries.
        ///    /// &lt;/summary&gt;
        ///    /// &lt;remarks&gt;
        ///    /// The Query Extension Pattern is pa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReadModelQueries {
            get {
                return ResourceManager.GetString("ReadModelQueries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Threading.Tasks;
        ///using System.Linq;
        ///using Slalom.Boost.Queries;
        ///using Slalom.Boost.Domain;
        ///using Slalom.Boost.Mapping;
        ///using Slalom.Boost;
        ///using {{RootNamespace}}.Domain.Model;
        ///
        ///namespace {{ProjectItem.ClassDescriptor.Namespace}}
        ///{
        ///	/// &lt;summary&gt;
        ///    /// Synchronizes a {{ProjectItem.ClassName.Humanize(LetterCasing.Title)}} on identified events.
        ///    /// &lt;/summary&gt;
        ///    /// &lt;seealso cref=&quot;Slalom.Boost.Domain.IEntity&quot; /&gt;
        ///    /// &lt;seealso cref=&quot;IReadModel&quot; /&gt;
        ///    ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Synchronizer {
            get {
                return ResourceManager.GetString("Synchronizer", resourceCulture);
            }
        }
    }
}
