//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Slalom.Boost.VisualStudio.Projects.Module.WebApi.Controllers.Files {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Templates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Templates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Slalom.Boost.VisualStudio.Projects.Module.WebApi.Controllers.Files.Templates", typeof(Templates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Linq;
        ///using System.Web.Http;
        ///using System.Web.Http.OData;
        ///using Slalom.Boost.WebApi.Controllers;
        ///using System.Threading.Tasks;
        ///using Slalom.Boost.WebApi.Controllers;
        ///
        ///namespace {{RootNamespace}}.Controllers
        ///{
        ///	// TODO: Remove AllowAnonymous if the user should authenticate
        ///
        ///    [RoutePrefix(&quot;admin&quot;), AllowAnonymous]
        ///    public class AdminController : BoostAdminController
        ///    {
        ///        [Route(&quot;command-results&quot;), HttpGet]
        ///        public override dynamic QueryCommandRe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AdminController {
            get {
                return ResourceManager.GetString("AdminController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Linq;
        ///using System.Web.Http;
        ///using System.Web.Http.OData;
        ///using Slalom.Boost.WebApi.Controllers;
        ///using System.Threading.Tasks;
        ///
        ///namespace {{RootNamespace}}.Controllers
        ///{
        ///    // TODO: Update the command names or create the commands
        ///    // TODO: Run the project to open Swagger and check the routes
        ///	// TODO: Remove AllowAnonymous if the user should authenticate
        ///	// TODO: Bind to IIS if not already bound
        ///
        ///    [RoutePrefix(&quot;{{NameLower}}&quot;), AllowAnonymous]
        ///    public cla [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CommandController {
            get {
                return ResourceManager.GetString("CommandController", resourceCulture);
            }
        }
    }
}
