// <auto-generated />

using System;
using System.Runtime.Serialization;
using System.Security.Permissions;

namespace Slalom.Boost.Dynamic.Exceptions
{
	[Serializable]
	public class DuplicateParameterException : DynamicExpressoException
	{
		public DuplicateParameterException(string identifier)
			: base(string.Format("The parameter '{0}' was defined more than once", identifier)) 
		{
			this.Identifier = identifier;
		}

		protected DuplicateParameterException(
			SerializationInfo info,
			StreamingContext context)
			: base(info, context) 
		{
			this.Identifier = info.GetString("Identifier");
		}

		public string Identifier { get; private set; }

		[SecurityPermission(SecurityAction.Demand, SerializationFormatter = true)]
		public override void GetObjectData(SerializationInfo info, StreamingContext context)
		{
			info.AddValue("Identifier", this.Identifier);

			base.GetObjectData(info, context);
		}
	}
}
