//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Slalom.Boost.VisualStudio.Projects.Module.Persistence.Files {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Templates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Templates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Slalom.Boost.VisualStudio.Projects.Module.Persistence.Files.Templates", typeof(Templates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.ComponentModel.DataAnnotations;
        ///using System.ComponentModel.DataAnnotations.Schema;
        ///
        ///namespace {{RootNamespace}}.Persistence.Model
        ///{
        ///	[Table(&quot;{{PluralEntityName}}&quot;)]
        ///    public class {{Entity}}
        ///    {
        ///		[Key]
        ///{{PropertyDeclaration}}
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string DataObject {
            get {
                return ResourceManager.GetString("DataObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Linq;
        ///using Slalom.Boost.Domain;
        ///using {{RootNamespace}}.Domain.Model;
        ///using System.Threading.Tasks;
        ///using System.Collections.Generic;
        ///using System.Data.Entity.Migrations;
        ///using System.Data.Entity;
        ///using Slalom.Boost.EntityFramework.Domain;
        ///
        ///namespace {{RootNamespace}}.Persistence.Domain
        ///{
        ///	/// &lt;summary&gt;
        ///    /// Provides a repository for &lt;see cref=&quot;{{Entity}}&quot; /&gt; instances.
        ///    /// &lt;/summary&gt;
        ///    /// &lt;seealso cref=&quot;IAggregateRoot&quot;/&gt;
        ///    /// &lt;seealso href=&quot;https://w [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EntityFrameworkRepository {
            get {
                return ResourceManager.GetString("EntityFrameworkRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Data.Entity.ModelConfiguration;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using {{Namespace}};
        ///
        ///// TODO: Update to appropriate table name.
        ///// TODO: Add any ignores if needed.
        ///
        ///namespace {{RootNamespace}}.Persistence.Queries
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Contains the EF mapping for the &lt;see cref=&quot;{{ReadModel}}&quot; /&gt; class.
        ///    /// &lt;/summary&gt;
        ///    /// &lt;remarks&gt;
        ///    /// There should be very little mapping needed  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EntityMapping {
            get {
                return ResourceManager.GetString("EntityMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Data.Entity.ModelConfiguration;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using {{Namespace}};
        ///
        ///// TODO: Update to appropriate table name.
        ///// TODO: Add any ignores if needed.
        ///
        ///namespace {{RootNamespace}}.Persistence.Application
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Contains the EF mapping for the &lt;see cref=&quot;{{ReadModel}}&quot; /&gt; class.
        ///    /// &lt;/summary&gt;
        ///    /// &lt;remarks&gt;
        ///    /// There should be very little mapping nee [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReadModelMapping {
            get {
                return ResourceManager.GetString("ReadModelMapping", resourceCulture);
            }
        }
    }
}
